### ISSUE TITLE
WIP: Opportunistic UX improvements

### ISSUE THREAD

**Issue by bedeho** [Joystream/apps#253]
While we resolve how to properly rebuild UX of the Pioneer app, the following list of smaller - but still valuable, improvements to the existing live version could be valuable in order to make it more user-friendly and functional. Please add additional suggestions in new comments below.

- Make a more relevant, Joystream specific, tab the default one, not the block production...
- By default, make _all_ application tabs visible, do not require login. Without login, show in view-only mode, and disable all extrinsic buttons, and emphasize signup.
- Remove validators app entirely, pointless.
- Remove my keys & addresses... again, not 100% pointless, but not worth it.
- Throw out all the pointless links that are largely irrelevant to most users. If badly needed, just put under a single Help tab or something.
- Make a membership-driven experience, users should never need to choose keys. Everything should be managed based on the active membership.
- A notification page which shows all relevant events and relevant calls to action for the given member.
- Factor out media related (browse, view, upload, download, my channel) stuff into a separate application outside of Pioneer.

**Comment by bwhm** [comment]
> Make a more relevant, Joystream specific, tab the default one, not the block production...

Agreed. We are making a landing page for `media` where there will be a video of the week, and other featured content. This would then be landing page until constantinople.

> By default, make all application tabs visible, do not require login...

Do you _really_ think it makes sense to show users:
   - Chain State
   - Extrinsics
   - Proposals (before we implement them)
   - Toolbox
   - Javascript

...by default?

> Remove validators app entirely, pointless.

Then user will have to manually construct extrinsics in order to setup their keys, stake, validate, unstake, etc. We can aggregate some of these tabs though...?

> Remove my keys & addresses...

Again, let's aggregate instead. You need a way to cycle between keys.

> Throw out all the pointless links that are largely irrelevant to most users.

Which ones?

> Factor out media related stuff...

Fully agree. No time for Rome though.

**Comment by bedeho** [comment]
Just to clarify, this is independent of Rome!

**Comment by bedeho** [comment]
Superseeded by ongoing https://github.com/Joystream/joystream/issues/400
